//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfDemo.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public long Id { get; set; }
        public long OrderId { get; set; }
        public string Item { get; set; }
        public int Quantity { get; set; }
        public decimal Rate { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public decimal Price { get; set; }
    }
}
